# Generated by Django 6.0.4 on 2026-04-11 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('plan', models.CharField(choices=[('3_dias', '3 días por semana'), ('5_dias', '5 días por semana')], help_text='Plan mensual del cliente', max_length=20)),
                ('telefono', models.CharField(blank=True, help_text='Telefono de contacto', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('estado_consulta', models.CharField(choices=[('ninguno', 'Ninguno'), ('pendiente', 'Pendiente consulta'), ('decidido', 'Decidido')], default='ninguno', help_text='Estado de consulta por inactividad', max_length=20)),
                ('fecha_ultima_consulta', models.DateField(blank=True, null=True)),
                ('turno', models.ForeignKey(help_text='Turno al que va cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='usuarios.turno')),
                ('usuario_creador', models.ForeignKey(help_text='Quien dio de alta al cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
