# Generated by Django 6.0.4 on 2026-04-14 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del plan (ej: 3_dias, 5_dias)', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del plan', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio mensual del plan', max_digits=10)),
                ('activo', models.BooleanField(default=True, help_text='Si el plan está disponible para nuevos clientes')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, help_text='Telefono de contacto', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('estado_consulta', models.CharField(choices=[('ninguno', 'Ninguno'), ('pendiente', 'Pendiente consulta'), ('decidido', 'Decidido')], default='ninguno', help_text='Estado de consulta por inactividad', max_length=20)),
                ('fecha_ultima_consulta', models.DateField(blank=True, null=True)),
                ('turno', models.ForeignKey(help_text='Turno al que va cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='usuarios.turno')),
                ('usuario_creador', models.ForeignKey(help_text='Quien dio de alta al cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(help_text='Plan contratado por el cliente', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clientes.plan')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
