# Generated by Django 6.0.4 on 2026-04-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del plan (ej: 3_dias, 5_dias)', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del plan', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio mensual del plan', max_digits=10)),
                ('activo', models.BooleanField(default=True, help_text='Si el plan está disponible para nuevos clientes')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
