# Generated by Django 6.0.4 on 2026-09-06 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio mensual vigente', max_digits=10)),
                ('vigencia_desde', models.DateField(help_text='Mes (normalizado a día 1) desde el que rige este precio')),
                ('plan', models.ForeignKey(help_text='Plan al que pertenece este precio', on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='clientes.plan')),
            ],
            options={
                'verbose_name': 'Precio de plan',
                'verbose_name_plural': 'Precios de planes',
                'ordering': ['vigencia_desde'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'vigencia_desde'), name='unique_precio_plan_vigencia')],
            },
        ),
    ]
