# Generated by Django 6.0.4 on 2026-04-13 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='plan_nuevo',
            field=models.ForeignKey(blank=True, help_text='Plan nuevo (FK) - temporal para migración', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_nuevo', to='clientes.plan'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='plan',
            field=models.CharField(choices=[('3_dias', '3 días por semana'), ('5_dias', '5 días por semana')], help_text='Plan contratado por el cliente', max_length=20),
        ),
    ]
