# Generated by Django 6.0.4 on 2026-04-14 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(help_text='Fecha registro del pago')),
                ('mes_cubierto', models.DateField(help_text='Mes que cubre el pago(se guarda como dia 1 del mes)')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto cobrado', max_digits=10)),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales(ej:"pago proporcional 9 dias", "pago por 2 dias esta semana")')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp del registro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='clientes.cliente')),
                ('usuario_registrador', models.ForeignKey(help_text='Usuario que registro este pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
