# Generated by Django 6.0.4 on 2026-08-23 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(fields=('cliente', 'mes_cubierto'), name='unique_pago_por_mes'),
        ),
    ]
