# Generated by Django 6.0.4 on 2026-09-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pago_unique_pago_por_mes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pago',
            name='unique_pago_por_mes',
        ),
    ]
